### ISSUE TITLE
Homework 2 Feedback

### ISSUE THREAD

**Issue by HeyStenson** [graceambrose/HW_002#1]
Well done! :palm_tree: 

**Readability of your code (1-3):**
3
**Does it run? (1-3):**
3
**Are best practices followed? (1-3):**
2

**Notes:**
There's a "white-tex” class on line 19 :grin: 
Think about ways to write fewer lines of code in your CSS by using the DRY principle (Don’t Repeat Yourself). For instance if most of your text is in the font Georgia, you can declare that at the body level, and then for the pieces that are in Arial, you could declare them once, like this:
`.main-nav li,
h2,
h3,
ul {
     font-family: Arial;
}`

**Comment by graceambrose** [comment]
Thank you! My homework for today is going to be late.. just too much going
on at work this week.

Grace
